"""Add suspended column to User

Revision ID: 421388cbdc75
Revises: 4c7819a06db8
Create Date: 2026-05-17 12:49:31.918076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421388cbdc75'
down_revision = '4c7819a06db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suspended')

    # ### end Alembic commands ###
