"""Add messages table

Revision ID: bc5ca457b5f9
Revises: 
Create Date: 2025-01-10 10:21:53.672424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5ca457b5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('stripe_subscription_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stripe_subscription_id',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
